# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Kotbase
site_url: https://kotbase.dev/
site_description: Kotlin Multiplatform library for Couchbase Lite—a lightweight, embedded, syncable, NoSQL database
site_author: Jeff Lockhart
copyright: "&copy; 2023 Jeff Lockhart"
repo_name: Kotbase
repo_url: https://github.com/jeffdgr8/kotbase
remote_branch: gh-pages
theme:
  name: material
  logo: assets/images/couchbase-logo.svg
  favicon: assets/images/couchbase-logo.svg
  font:
    text: DM Sans
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      link: material/link
      important: material/lightbulb-on
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
extra_css:
  - assets/stylesheets/permalink.css
  - assets/stylesheets/extra.css
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: ""
  - footnotes
  - md_in_html
plugins:
  - search
  - macros
extra:
  version: 3.0.12-1.0.0
  version_objc: 3.0.12
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/jeffdgr8
    - icon: simple/x
      link: https://twitter.com/jeffdgr8
    - icon: simple/linkedin
      link: https://linkedin.com/in/lockhartjeff/
nav:
  - Overview:
    - Kotbase: index.md
    - Differences from Couchbase Lite Java SDK: differences.md
    - Extensions:
      - KTX: ktx.md
      - Kermit: kermit.md
      - Paging: paging.md
    - Roadmap: roadmap.md
    - Community: community.md
    - License: license.md
  - Getting Started:
    - Installation: installation.md
    - Supported Platforms: platforms.md
    - Build and Run: getting-started.md
  - Documentation:
    - Databases: databases.md
    - Pre-built Database: prebuilt-database.md
    - Documents: documents.md
    - Blobs: blobs.md
    - Query:
      - QueryBuilder: query-builder.md
      - SQL++ Query Strings: n1ql-query-strings.md
      - SQL++ Server Differences: n1ql-server-differences.md
      - SQL++ QueryBuilder Differences: n1ql-query-builder-differences.md
      - Query Result Sets: query-result-sets.md
      - Live Queries: live-queries.md
      - Query Troubleshooting: query-troubleshooting.md
    - Full Text Search: full-text-search.md
    - Indexing: indexing.md
    - Data Sync:
      - Remote Sync Gateway: remote-sync-gateway.md
      - Intra-device Sync: intra-device-sync.md
      - Peer-to-Peer:
        - Peer-to-Peer Sync: peer-to-peer-sync.md
        - Passive Peer: passive-peer.md
        - Active Peer: active-peer.md
        - Integrate Custom Listener: integrate-custom-listener.md
    - Handling Data Conflicts: handling-data-conflicts.md
    - Using Logs: using-logs.md
    - Kotlin Extensions: kotlin-extensions.md
  - API Reference: api" target="_blank
