[versions]
activity-compose = "1.7.2"
android-gradle-plugin = "8.1.1"
androidx-appcompat = "1.6.1"
androidx-core-ktx = "1.10.1"
compose = "1.5.0"
couchbase-lite-objc = "3.0.12"
kotbase = "3.0.12-1.0.0-SNAPSHOT"
kotlin = "1.9.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
kotbase = { module = "dev.kotbase:couchbase-lite-ktx", version.ref = "kotbase" }
