package com.udobny.kmp.couchbase.lite.ktx.paging3

import app.cash.paging.PagingSource
import com.couchbase.lite.kmp.Database
import com.couchbase.lite.kmp.ListenerToken
import com.couchbase.lite.kmp.Query
import com.udobny.kmp.IO
import kotlinx.coroutines.Dispatchers
import kotlin.coroutines.CoroutineContext
import kotlin.properties.Delegates

internal abstract class QueryPagingSource<Key : Any, RowType : Any> :
    PagingSource<Key, RowType>() {

    private var listenerToken: ListenerToken? = null
    private var firstResult = true

    protected var currentQuery: Query? by Delegates.observable(null) { _, old, new ->
        listenerToken?.let {
            old?.removeChangeListener(it)
        }
        firstResult = true
        listenerToken = new?.addChangeListener {
            if (firstResult) {
                firstResult = false
            } else {
                invalidate()
            }
        }
    }

    init {
        registerInvalidatedCallback {
            listenerToken?.let {
                currentQuery?.removeChangeListener(it)
            }
            listenerToken = null
            currentQuery = null
        }
    }
}

/**
 * Create a [PagingSource] that pages through results according to queries generated by
 * [queryProvider]. Queries returned by [queryProvider] should expect to do SQL offset/limit
 * based paging. For that reason, [countQuery] is required to calculate pages and page offsets.
 *
 * An example query returned by [queryProvider] could look like:
 *
 * ```sql
 * SELECT value FROM numbers
 * LIMIT 10
 * OFFSET 100;
 * ```
 *
 * Queries will be executed on [context].
 */
@Suppress("FunctionName")
public fun <RowType : Any> QueryPagingSource(
    countQuery: Query,
    mapper: (Map<String, Any?>) -> RowType,
    database: Database,
    context: CoroutineContext = Dispatchers.IO,
    queryProvider: (limit: Int, offset: Int) -> Query,
): PagingSource<Int, RowType> = OffsetQueryPagingSource(
    queryProvider,
    countQuery,
    mapper,
    database,
    context
)
