# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Run tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run macOS tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Run tests
        run: ./gradlew check
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: macos-test-results
          path: ./**/build/reports/tests

  linux-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Linux tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Install libicu
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2.1_amd64.deb
          sudo dpkg -i libicu66_66.1-2ubuntu2.1_amd64.deb
          rm libicu66_66.1-2ubuntu2.1_amd64.deb
          wget https://launchpad.net/ubuntu/+source/icu/71.1-2/+build/23579523/+files/libicu71_71.1-2_amd64.deb
          sudo dpkg -i libicu71_71.1-2_amd64.deb
          rm libicu71_71.1-2_amd64.deb
      - name: Run tests
        run: ./gradlew check
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: linux-test-results
          path: ./**/build/reports/tests

  windows-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Windows tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Run tests
        run: ./gradlew check --no-daemon --no-parallel "-Dorg.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=500m"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: windows-test-results
          path: ./**/build/reports/tests

  android-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Android tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          ram-size: 4096M
          script: ./gradlew connectedCheck --no-parallel
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: android-test-results
          path: ./**/build/reports/androidTests
