# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Run tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx3g -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  macos-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run macOS tests
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Run tests
        run: ./gradlew check
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: macos-test-results
          path: ./**/build/reports/tests

  linux-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Linux tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Install libicu
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2.1_amd64.deb
          sudo dpkg -i libicu66_66.1-2ubuntu2.1_amd64.deb
          rm libicu66_66.1-2ubuntu2.1_amd64.deb
          wget https://launchpad.net/ubuntu/+source/icu/71.1-2/+build/23579523/+files/libicu71_71.1-2_amd64.deb
          sudo dpkg -i libicu71_71.1-2_amd64.deb
          rm libicu71_71.1-2_amd64.deb
      - name: Run tests
        run: ./gradlew check
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: linux-test-results
          path: ./**/build/reports/tests

  windows-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Windows tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Run tests
        run: ./gradlew check "-Dorg.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=500m"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: windows-test-results
          path: ./**/build/reports/tests

  android-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Android tests
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: arm64-v8a
          script: ./gradlew connectedCheck
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: android-test-results
          path: ./**/build/reports/androidTests
