# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Run tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.parallel=false -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  macos-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run macOS tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
      - name: Run tests
        run: ./gradlew check
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: macos-test-results
          path: |
            ./**/build/reports/tests
            ./**/*.log

  linux-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Linux tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
      - name: Install libicu
        run: |
          wget https://launchpadlibrarian.net/626467203/libicu71_71.1-3ubuntu1_amd64.deb
          sudo dpkg -i libicu71_71.1-3ubuntu1_amd64.deb
          rm libicu71_71.1-3ubuntu1_amd64.deb
      - name: Run tests
        run: ./gradlew check
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: linux-test-results
          path: |
            ./**/build/reports/tests
            ./**/*.log

  windows-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Windows tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
      - name: Run tests
        run: ./gradlew check
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: windows-test-results
          path: |
            ./**/build/reports/tests
            ./**/*.log

  android-tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Run Android tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          script: ./gradlew androidConnectedCheck
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: android-test-results
          path: |
            ./**/build/reports/androidTests
            ./**/*.log
